--Set current turn on insert
DELIMITER ;;

CREATE TRIGGER `$TG_ACTION_BITG`
BEFORE INSERT
ON `ACTION` FOR EACH ROW
BEGIN
	IF NEW.ACTI_TURN IS NULL THEN
		SET NEW.ACTI_TURN = GET_CURRENT_TURN();
	END IF;
END;;

CREATE TRIGGER `$TG_BUILDING_BITG`
BEFORE INSERT
ON BUILDING FOR EACH ROW
BEGIN 
	IF NEW.BUIL_TURN_BUILT IS NULL THEN
		SET NEW.BUIL_TURN_BUILT = GET_CURRENT_TURN();
	END IF;
END;;

CREATE TRIGGER `$TG_SETTLEMENT_BITG`
BEFORE INSERT
ON SETTLEMENT FOR EACH ROW
BEGIN 
	IF NEW.SETT_TURN_FOUNDED IS NULL THEN
		SET NEW.SETT_TURN_FOUNDED = GET_CURRENT_TURN();
	END IF;
END;;

CREATE TRIGGER `$TG_TURN_BITG`
BEFORE INSERT
ON TURN FOR EACH ROW
BEGIN 
	UPDATE TURN SET TURN_ACTIVE = FALSE, TURN_END_DATE = CURRENT_TIMESTAMP() WHERE TURN_GUID = GET_CURRENT_TURN();	
END;;

CREATE TRIGGER `$TG_UNIT_INSTANCE_BITG`
BEFORE INSERT
ON UNIT_INSTANCE FOR EACH ROW
BEGIN
	IF NEW.UNIN_TURN_DEPLOYED IS NULL THEN
		SET NEW.UNIN_TURN_DEPLOYED = GET_CURRENT_TURN();
	END IF;
END;;

DELIMITER ;