/*
 * Defines the starting resources for a given settlement type
 */
CREATE TABLE `SETTLEMENT_TYPE_ECONOMY_VALUES` (
  `STEV_SETTLEMENT_TYPE` varchar(100) NOT NULL,
  `STEV_RESOURCE_TYPE` varchar(100) NOT NULL,
  `STEV_FACTOR` mediumint(9) NOT NULL DEFAULT 0,
  KEY `SETTLEMENT_TYPE_ECONOMY_VALUES_RESOURCE_TYPE_FK` (`STEV_RESOURCE_TYPE`),
  KEY `SETTLEMENT_TYPE_ECONOMY_VALUES_SETTLEMENT_TYPE_FK` (`STEV_SETTLEMENT_TYPE`),
  CONSTRAINT `SETTLEMENT_TYPE_ECONOMY_VALUES_RESOURCE_TYPE_FK` FOREIGN KEY (`STEV_RESOURCE_TYPE`) REFERENCES `RESOURCE_TYPE` (`RETY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SETTLEMENT_TYPE_ECONOMY_VALUES_SETTLEMENT_TYPE_FK` FOREIGN KEY (`STEV_SETTLEMENT_TYPE`) REFERENCES `SETTLEMENT_TYPE` (`SETY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT='Defines the starting resources per settlement type';