/*
 * Config that defines which building can be placed at which settlement type
 */
CREATE TABLE `SETTLEMENT_TYPE_BUILDING_CONSTRAINTS` (
  `STBC_SETTLEMENT_TYPE` varchar(100) NOT NULL,
  `STBC_BUILDING_TYPE` varchar(100) NOT NULL,
  KEY `SETTLEMENT_TYPE_BUILDING_CONSTRAINTS_SETTLEMENT_TYPE_FK` (`STBC_SETTLEMENT_TYPE`),
  KEY `SETTLEMENT_TYPE_BUILDING_CONSTRAINTS_BUILDING_TYPE_FK` (`STBC_BUILDING_TYPE`),
  CONSTRAINT `SETTLEMENT_TYPE_BUILDING_CONSTRAINTS_BUILDING_TYPE_FK` FOREIGN KEY (`STBC_BUILDING_TYPE`) REFERENCES `BUILDING_TYPE` (`BUTY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SETTLEMENT_TYPE_BUILDING_CONSTRAINTS_SETTLEMENT_TYPE_FK` FOREIGN KEY (`STBC_SETTLEMENT_TYPE`) REFERENCES `SETTLEMENT_TYPE` (`SETY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT='Config table that represents which building can be put down at which settlement type';