/*
 * Belongs to exactly one TRADE_ROUTE
 * Represents the content of a trade route
 */
CREATE TABLE `TRADE_ROUTE_RESOURCES` (
  `TRRE_ROUTE` uuid NOT NULL,
  `TRRE_RESOURCE_TYPE` varchar(100) NOT NULL,
  `TRRE_AMOUNT` mediumint(8) unsigned NOT NULL DEFAULT 0,
  KEY `TRADE_ROUTE_RESOURCES_RESOURCE_TYPE_FK` (`TRRE_RESOURCE_TYPE`),
  KEY `TRADE_ROUTE_RESOURCES_TRADE_ROUTE_FK` (`TRRE_ROUTE`),
  CONSTRAINT `TRADE_ROUTE_RESOURCES_RESOURCE_TYPE_FK` FOREIGN KEY (`TRRE_RESOURCE_TYPE`) REFERENCES `RESOURCE_TYPE` (`RETY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TRADE_ROUTE_RESOURCES_TRADE_ROUTE_FK` FOREIGN KEY (`TRRE_ROUTE`) REFERENCES `TRADE_ROUTE` (`TRRO_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE
) COMMENT='Represents the content of a trade route';