/*
 * Resource costs per unit type
 * Used to calculate repair, upkeep and production costs
 * 1:1 associated with a UNIT_TYPE
 */
CREATE TABLE `UNIT_TYPE_COSTS` (
  `UTYC_TYPE` varchar(100) NOT NULL,
  `UTYC_RESOURCE_TYPE` varchar(100) NOT NULL,
  `UTYC_CONSUMPTION_RATE` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `UTYC_CONSTRUCTION_COST` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `UTYC_REPAIR_COSTS` mediumint(8) unsigned NOT NULL DEFAULT 0,
  KEY `UNIT_TYPE_COSTS_UNIT_TYPE_FK` (`UTYC_TYPE`),
  KEY `UNIT_TYPE_COSTS_RESOURCE_TYPE_FK` (`UTYC_RESOURCE_TYPE`),
  CONSTRAINT `UNIT_TYPE_COSTS_RESOURCE_TYPE_FK` FOREIGN KEY (`UTYC_RESOURCE_TYPE`) REFERENCES `RESOURCE_TYPE` (`RETY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `UNIT_TYPE_COSTS_UNIT_TYPE_FK` FOREIGN KEY (`UTYC_TYPE`) REFERENCES `UNIT_TYPE` (`UNTY_IDENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Cost table for a given unit type';